image: "fpco/stack-build:lts-23.1"

variables:
  STACK_ROOT: ${CI_PROJECT_DIR}/.stack

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .stack
    - .stack-work

stages:
  - lint-format
  - build-test

haskell-lint-format:
  stage: lint-format
  script:
    - stack install hlint ormolu
    - stack exec hlint .
    - find src app test -name "*.hs" -exec stack exec ormolu -- --mode check {} +

haskell-build-test:
  stage: build-test
  script:
    - stack build
    - stack test
    - stack exec first-task
    - stack exec second-task
