image: registry.gitlab.se.ifmo.ru/courses/haskell/fp-practice/base:latest

variables:
  STACK_ROOT: ${CI_PROJECT_DIR}/.stack

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .stack
    - .stack-work

stages:
  - lint-format
  - build-test


haskell-lint-format:
  stage: lint-format
  script:
    - echo "Linting and formatting Haskell..."
    - hlint .
    - find src app test -name "*.hs" -exec ormolu -- --mode check {} +
  allow_failure: true 

haskell-build-test-run:
  stage: build-test
  script:
    - echo "Building, testing, and running Haskell..."
    - stack build --test --no-run-tests
    - stack test
    - stack exec first-task
    - stack exec second-task
